# Generated by Django 3.0.3 on 2020-06-07 15:56
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("designation", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Hospital",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, unique=True)),
                ("address", models.TextField()),
                ("city", models.CharField(max_length=1000)),
                ("state", models.CharField(max_length=1000)),
                ("country", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("age", models.IntegerField()),
                (
                    "admitted_in",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hrm.Hospital"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PatientRegistry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000)),
                ("age", models.IntegerField()),
                ("designation", models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name="Wards",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, null=True)),
                (
                    "hospital",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hrm.Hospital"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StaffRegistry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hrm.Hospital",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hrm.Staff",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="staff",
            name="attached_to",
            field=models.ManyToManyField(
                through="hrm.StaffRegistry", to="hrm.Hospital"
            ),
        ),
        migrations.CreateModel(
            name="Prescriptions",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("details", models.TextField()),
                (
                    "by_doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hrm.Doctor",
                    ),
                ),
                (
                    "for_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hrm.Patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OtNotes",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "filled_by",
                    models.CharField(
                        choices=[("doctor", 1), ("staff", 2)], max_length=1000
                    ),
                ),
                ("details", models.TextField(null=True)),
                (
                    "for_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hrm.Patient"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DoctorRegistry",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hrm.Doctor",
                    ),
                ),
                (
                    "hospital",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="hrm.Hospital",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="doctor",
            name="attached_to",
            field=models.ManyToManyField(
                through="hrm.DoctorRegistry", to="hrm.Hospital"
            ),
        ),
        migrations.CreateModel(
            name="Beds",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.IntegerField()),
                (
                    "ward",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="hrm.Wards"
                    ),
                ),
            ],
        ),
    ]
