apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose --file docker-compose.yml convert --out manifests/
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: backend
  name: backend
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 8000
  - name: "8090"
    port: 8090
    targetPort: 8090
  selector:
    io.kompose.service: backend
status:
  loadBalancer: {}
