# Generated by Django 3.0.7 on 2020-12-11 12:19
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_zero", "0002_auto_20201207_1253"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="user_type",
        ),
        migrations.CreateModel(
            name="AccountType",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_type_level",
                    models.CharField(
                        choices=[
                            ("ADMIN", "admin"),
                            ("STAFF", "staff"),
                            ("SUPPORT", "support"),
                            ("PATIENT", "patient"),
                        ],
                        default="PATIENT",
                        max_length=20,
                        unique=True,
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="account_types", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
