"""
Django settings for covidX project.

Generated by 'django-admin startproject' using Django 3.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""
import functools
import glob
import os

import requests
from dotenv import load_dotenv

import covidX.gae_settings as gae  # pylint: disable=no-name-in-module
import covidX.utils as utils  # pylint: disable=no-name-in-module

PROJECT_NAME = "covidX"
# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
SETTINGS_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.dirname(SETTINGS_DIR)
PROJECT_ROOT = os.path.expanduser(BASE_DIR)
join_project_path = functools.partial(os.path.join, PROJECT_ROOT)

# load LOGGER
LOGGER = utils.createLogger(join_project_path("logs.log"))

# load variables values into ENV
ENV = join_project_path(".env")
load_dotenv(ENV, verbose=True, override=True)

LOGGER.info(f"Starting {PROJECT_NAME} app")
LOGGER.info(f"PROJECT_ROOT= {PROJECT_ROOT}")

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
        "TIMEOUT": 1800,
    }
}

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/


# SECURITY WARNING: keep the secret key used in production secret!
# When running on GAE, access from gcp secret manager.
SECRET_KEY = os.getenv("SECRET_KEY", gae.access_secret_key_version())

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = bool(os.getenv("DEBUG_ENV", None))

ALLOWED_HOSTS = "0.0.0.0"

# Application definition
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

PLUGIN_APPS = [
    "corsheaders",
    "social_django",
    "django_extensions",
    "guardian",
    "graphene_django",
    "rest_framework",
    "rest_framework_jwt",
    "rest_framework_jwt.blacklist",
    "phonenumber_field",
]

MODULES = [
    # TODO(codecakes): add "algoliasearch_django" when needed,
    "apps.hrm",
    "apps.apihealth",
    "apps.auth_zero",
]

INSTALLED_APPS = DJANGO_APPS + PLUGIN_APPS + MODULES

MIDDLEWARE = [
    "debug_toolbar.middleware.DebugToolbarMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    # Map username from the Access Token payload to
    # Django authentication system
    "django.contrib.auth.middleware.RemoteUserMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "social_django.middleware.SocialAuthExceptionMiddleware",
]

ROOT_URLCONF = "covidX.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": glob.glob(join_project_path("apps/*/templates")),
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                # See:
                # https://python-social-auth.readthedocs.io/en/latest/configuration/django.html#template-context-processors
                "social_django.context_processors.backends",
                "social_django.context_processors.login_redirect",
            ]
        },
    },
]

WSGI_APPLICATION = "covidX.wsgi.application"

ASGI_APPLICATION = "covidX.asgi.application"

# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

if not DEBUG:
    GAE_APPLICATION = os.getenv("GAE_APPLICATION")
    CONNECTION_NAME = os.getenv("CONNECTION_NAME")
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql_psycopg2",
            "HOST": f"/cloudsql/{CONNECTION_NAME}",
            "USER": f'{os.getenv("DB_USER")}',
            "PASSWORD": f'{os.getenv("DB_PWD")}',
            "NAME": f'{os.getenv("DB_NAME")}',
        }
    }

# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        # pylint: disable=line-too-long
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/
STATIC_ROOT = join_project_path("static")
STATIC_URL = "/static/"

if not os.path.exists(STATIC_ROOT):
    os.makedirs(STATIC_ROOT)

# SOCIAL AUTH AUTH0 BACKEND CONFIG
SOCIAL_AUTH_TRAILING_SLASH = os.getenv("SOCIAL_AUTH_TRAILING_SLASH")
SOCIAL_AUTH_AUTH0_KEY = os.environ.get("SOCIAL_AUTH_AUTH0_KEY")
SOCIAL_AUTH_AUTH0_SECRET = os.environ.get("SOCIAL_AUTH_AUTH0_SECRET")
SOCIAL_AUTH_AUTH0_SCOPE = ["openid", "profile", "email"]
SOCIAL_AUTH_AUTH0_DOMAIN = os.environ.get("SOCIAL_AUTH_AUTH0_DOMAIN")
SOCIAL_AUTH_ACCESS_TOKEN_METHOD = os.getenv("ACCESS_TOKEN_METHOD")
SOCIAL_AUTH_RAISE_EXCEPTIONS = True
SOCIAL_AUTH_POSTGRES_JSONFIELD = True
SOCIAL_AUTH_REVOKE_TOKENS_ON_DISCONNECT = True
SOCIAL_AUTH_ADMIN_USER_SEARCH_FIELDS = [
    "username",
    "first_name",
    "last_name",
    "email",
]
AUTH_USER_MODEL = "auth_zero.User"
SOCIAL_AUTH_USER_MODEL = AUTH_USER_MODEL

JWT_AUDIENCE = os.getenv("JWT_AUDIENCE")

LOGIN_URL = "/auth0/login/auth0"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
AUTH_REDIRECT_URI = "/auth0/complete/auth0"

# auth0 settings
AUTH0_ALGORITHMS = ["RS256"]
if AUTH0_DOMAIN := os.getenv("SOCIAL_AUTH_AUTH0_DOMAIN"):
    JWT_ISSUER = f"https://{AUTH0_DOMAIN}/"
if JWT_AUDIENCE:
    SOCIAL_AUTH_AUTH0_AUTH_EXTRA_ARGUMENTS = {"audience": JWT_AUDIENCE}
AUTH0_JWKS = requests.get(
    f"https://{SOCIAL_AUTH_AUTH0_DOMAIN}/.well-known/jwks.json"
).json()

# TODO(codecakes): enable logic once code auth flow tested.
# Set JWT_AUDIENCE to API identifier and
# the JWT_ISSUER to Auth0 domain
JWT_AUTH = {
    "JWT_PAYLOAD_GET_USERNAME_HANDLER": (
        "apps.auth_zero.auth0backend."
        "Auth0CodeFlow.jwt_get_username_from_payload_handler"
    ),
    "JWT_DECODE_HANDLER": (
        "apps.auth_zero.auth0backend.Auth0CodeFlow.jwt_decode_token"
    ),
    "JWT_ALGORITHM": "RS256",
    "JWT_AUDIENCE": JWT_AUDIENCE,
    "JWT_ISSUER": JWT_ISSUER,
    "JWT_AUTH_HEADER_PREFIX": "Bearer",
}

AUTHENTICATION_BACKENDS = {
    "apps.auth_zero.auth0backend.Auth0",
    "django.contrib.auth.backends.ModelBackend",
    "django.contrib.auth.backends.RemoteUserBackend",
    "guardian.backends.ObjectPermissionBackend",
}

# rest framework settings from drf-jwt
REST_FRAMEWORK = {
    # Use Django's standard `django.contrib.auth` permissions,
    # or allow read-only access for unauthenticated users.
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_jwt.authentication.JSONWebTokenAuthentication",
        "rest_framework.authentication.SessionAuthentication",
        "rest_framework.authentication.BasicAuthentication",
    ],
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.BrowsableAPIRenderer",
        "rest_framework.renderers.JSONOpenAPIRenderer",
    ],
}


# See: https://django-guardian.readthedocs.io/en/stable/\
# configuration.html#guardian-raise-403
GUARDIAN_RENDER_403 = True

GRAPHENE = {
    "SCHEMA": "covidX.schema.schema",
    "SCHEMA_OUTPUT": "schema.json",
    "SCHEMA_INDENT": 2,
}

ALGOLIA = {
    "APPLICATION_ID": os.getenv("ALGOLIA_APPLICATION_ID"),
    "API_KEY": os.getenv("ALGOLIA_API_KEY"),
}
